FORMAT: 1A
HOST: http://www.virtual-address.space

# Virtual Address Space

Virtual Address Space provides new hires with all the knowledge they
need to inform them on which city they should move to after college.

## States [/api/States]
### Which State Are You Thinking Of Moving To? [GET]

+ Response 200 (application/json)

        {
        "California": {
            "Statecode": "CA",
            "Statename": "California".
            "Longitutde": 36.7783,
            "Latitude": 119.4179
            },
        "New York": {
            "Statecode": "NY",
            "Statename": "New York".
            "Longitutde": 40.7128,
            "Latitude": 74.0059
                    },
        "Texas": {
            "Statecode": "TX",
            "Statename": "Texas".
            "Longitutde": 31.9686,
            "Latitude": 99.9018
                }
        }

## Specific State [/api/States/{Stateid}]

### Pick A State [GET]

+ Parameters
    + Stateid (required, string) 

+ Response 200 (application/json)

        {
            "Stateid": {
            "California":{
                "Week_Of": 2016-03-22,
                "Property Type": "All,
                "Average_Listing_Price": 225000,
                "Median_Listing_Price": 300000,
                "Num_Properties": 300,
                "State_code": "CA" 
                    }
        }

##Cities [/api/Cities]

### Now Lets Look At Some Cities [GET]

What cities are you thinking about living in?

+ Response 200 (application/json)

        {
            "Cities":[{    
                "Austin": {
                "City_name": "Austin",
                "City_id": 1,
                "State_code": "TX",
                "Longitude": 30.2672,
                "Latitude": 97.7431
                },
                "Houston": {
                "City_name": "Houston",
                "City_id": 2,
                "State_code": "TX",
                "Longitude": 29.7604,
                "Latitude": 95.3698
                },
                "Dallas": {
                "City_name": "Dallas",
                "City_id": 3,
                "State_code": "TX",
                "Longitude": 29.7604,
                "Latitude": 95.3698
            }]
        }
        

## Specific City [/api/cities/{City_id}]
### Pick A Specific City [GET]

+ Parameters
    + City_id(required, Integer) - name of the city
     
+ Response 200 (application/json)

        {
            "City":[{    
                "Austin": {
                "City": "Austin": 
                "City_id": 1,
                "Week_Of": 2016-03-22,
                "Property Type": "All",
                "Average_Listing_Price": 225000,
                "Median_Listing_Price": 300000,
                "Num_Properties": 300,
                "State_code": "TX" 
                    }
                }        
        }

## Neighborhoods [/api/neighborhood]

### Now which neighborhood? [GET]

What neighborhood are you thinking about living in?

+ Response 200 (application/json)

        {
                "Castro":{
                "Neighborhood_name": "Castro",
                "Neighborhood_ID": 1394,
                "City_name": "San Francisco",
                "City_ID": 1,
                "State_Code": "CA",
                "Property Type": "All Properties",
                    },
        }

##Specific Neighborhood [/api/Neighborhoods/{neighborhoodID}]

### Pick A Particular Neighborhood [GET]


+ Parameters
    + neighborhoodID(required, integer) - ID number of the neighborhood
        
+ Response 200 (application/json)

        {
                "Castro":{
                "Neighborhood_name": "Castro",
                "neighborhoodID": 1394,
                "City_name": "San Fransisco",
                "StateID": "CA",
                "Property Type": "All Properties",
                "Num_Properties": 10,
                "Avg Listing": 849000,
    
                    },
        }

